name: pet_home
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter_credit_card: ^2.0.0
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.4
  firebase_database: ^10.0.9
  flutter_switch: ^0.3.2
  nb_utils: ^4.6.25
  uuid: ^3.0.7
  intl: ^0.17.0
  flutter_tawk: ^0.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
 
  syncfusion_flutter_calendar: ^20.4.38
  shared_preferences: ^2.0.15
  image_picker: ^0.8.6
  flutter_profile_picture: ^2.0.0
  editable_image: ^1.1.0
  path_provider: ^2.0.5
  path: ^1.8.0
  cr_calendar: ^1.0.0+1
  time_planner: ^0.1.1
  flutter_clean_calendar: ^1.1.0
  table_calendar: ^3.0.0

  provider: ^6.0.5
  riverpod: ^2.1.3
  cloud_firestore: ^4.3.1

  animated_splash_screen: ^1.3.0
  introduction_screen: ^3.1.2

  smooth_page_indicator: ^1.0.0+2
  flutter_iconly: ^1.0.2

  google_fonts: ^3.0.1


  get: ^4.1.4
  flutter_lints: ^2.0.0

  


flutter:

  uses-material-design: true

  assets:
    - images/